// src/components/utils/link-tag-nuxt/LinkTag.vue
<script setup lang="ts">
import { computed } from "vue";
import { NuxtLink } from "#components";

interface LinkTagProps {
  /**
   * URL or path to navigate to
   */
  href?: string;

  /**
   * When true, renders as <div> instead of <a>
   */
  noLink?: boolean;

  /**
   * When true, uses href directly instead of processing via router
   */
  external?: boolean;

  /**
   * When true, opens link in new tab with target="_blank"
   */
  newTab?: boolean;

  /**
   * Additional attributes to pass to the element
   */
  attributes?: Record<string, unknown>;
}

const props = withDefaults(defineProps<LinkTagProps>(), {
  href: "",
  noLink: false,
  external: false,
  newTab: false,
});

// Get the component type based on props
const is = computed(() => {
  if (props.noLink) return "div" as const;
  if (props.external) return "a" as const;
  return NuxtLink;
});

// Determine target attribute
const target = computed<"_blank" | "">(() => (props.newTab ? "_blank" : ""));

// Build the link attributes
const link = computed(() => {
  // No link means no attributes for <div>
  if (props.noLink) {
    return { ...props.attributes };
  }

  // For external links
  if (props.external) {
    return {
      href: props.href,
      target: target.value,
      ...(props.newTab ? { rel: "noopener noreferrer" } : {}),
      ...props.attributes,
    };
  }

  // For NuxtLink
  return {
    to: props.href,
    target: target.value || undefined,
    ...props.attributes,
  };
});
</script>

<template>
  <component :is="is" v-bind="link">
    <slot />
  </component>
</template>

// src/snippets/utils/link-tag/react-next/LinkTag.tsx
import Link from "next/link";
import type { AnchorHTMLAttributes, ReactNode } from "react";

/**
 * LinkTag (React / Next.js) — a universal link.
 *
 * Renders the most appropriate element for the context:
 *  - next/link <Link> for internal navigation
 *  - a plain <a> for external URLs
 *  - a <div> when you want the children without any navigation
 */

interface LinkTagProps
  extends Omit<AnchorHTMLAttributes<HTMLAnchorElement>, "href"> {
  /** URL or path to navigate to. */
  href?: string;
  /** Render a <div> instead of a link. */
  noLink?: boolean;
  /** Treat href as an external URL — a plain <a>. */
  external?: boolean;
  /** Open in a new tab (sets target="_blank" + safe rel). */
  newTab?: boolean;
  children?: ReactNode;
}

export function LinkTag({
  href = "",
  noLink = false,
  external = false,
  newTab = false,
  children,
  ...attributes
}: LinkTagProps) {
  const target = newTab ? "_blank" : undefined;
  const rel = newTab ? "noopener noreferrer" : undefined;

  if (noLink) {
    return <div {...attributes}>{children}</div>;
  }

  if (external) {
    return (
      <a href={href} target={target} rel={rel} {...attributes}>
        {children}
      </a>
    );
  }

  return (
    <Link href={href} target={target} rel={rel} {...attributes}>
      {children}
    </Link>
  );
}

export default LinkTag;
